name: License checker

on:
  push:
    branches:
      - maste
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
